/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epic.system;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Erick Ivan
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBarra = new javax.swing.JPanel();
        jpCerrar = new javax.swing.JPanel();
        iconCerrar = new javax.swing.JLabel();
        jpLogo = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        jpSistema = new javax.swing.JPanel();
        textSistema = new javax.swing.JLabel();
        jpIconosI = new javax.swing.JPanel();
        jpCRM = new javax.swing.JPanel();
        iconCRM = new javax.swing.JLabel();
        textCRM = new javax.swing.JLabel();
        jpVentas = new javax.swing.JPanel();
        textVentas = new javax.swing.JLabel();
        iconVentas = new javax.swing.JLabel();
        jpProvedores = new javax.swing.JPanel();
        iconProvedores = new javax.swing.JLabel();
        textProvedores = new javax.swing.JLabel();
        jpDeudasP = new javax.swing.JPanel();
        iconDeudasP = new javax.swing.JLabel();
        textDeudasP = new javax.swing.JLabel();
        jpDeudasC = new javax.swing.JPanel();
        iconDeudasC = new javax.swing.JLabel();
        textDeudasC = new javax.swing.JLabel();
        jpEquipo = new javax.swing.JPanel();
        iconDeudasC1 = new javax.swing.JLabel();
        textDeudasC1 = new javax.swing.JLabel();
        jpIconosD = new javax.swing.JPanel();
        jpCRM1 = new javax.swing.JPanel();
        iconInventario = new javax.swing.JLabel();
        textInventario = new javax.swing.JLabel();
        jpInventario = new javax.swing.JPanel();
        textPacks = new javax.swing.JLabel();
        iconPacks = new javax.swing.JLabel();
        jpSuministros = new javax.swing.JPanel();
        iconSuministros = new javax.swing.JLabel();
        textSuministros = new javax.swing.JLabel();
        jpCuentas = new javax.swing.JPanel();
        iconCuentas = new javax.swing.JLabel();
        textCuentas = new javax.swing.JLabel();
        jpEstrategia = new javax.swing.JPanel();
        iconEstrategia = new javax.swing.JLabel();
        textEstrategia = new javax.swing.JLabel();
        jpPlaneacion = new javax.swing.JPanel();
        iconPlaneacion = new javax.swing.JLabel();
        textPlaneacion = new javax.swing.JLabel();
        jpCompras = new javax.swing.JPanel();
        iconCompras = new javax.swing.JLabel();
        textCompras = new javax.swing.JLabel();
        jpFacturacion = new javax.swing.JPanel();
        iconFacturacion = new javax.swing.JLabel();
        textFacturacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBarra.setBackground(new java.awt.Color(0, 0, 0));
        jpBarra.setPreferredSize(new java.awt.Dimension(1920, 80));
        jpBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCerrar.setBackground(new java.awt.Color(51, 51, 51));
        jpCerrar.setPreferredSize(new java.awt.Dimension(70, 50));
        jpCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCerrarMouseClicked(evt);
            }
        });
        jpCerrar.setLayout(new java.awt.BorderLayout());

        iconCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jpCerrar.add(iconCerrar, java.awt.BorderLayout.CENTER);

        jpBarra.add(jpCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, -1, -1));

        jpLogo.setBackground(new java.awt.Color(0, 0, 0));
        jpLogo.setLayout(new java.awt.BorderLayout());

        iconLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jpLogo.add(iconLogo, java.awt.BorderLayout.CENTER);

        jpBarra.add(jpLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jpSistema.setBackground(new java.awt.Color(0, 0, 0));
        jpSistema.setLayout(new java.awt.BorderLayout());

        textSistema.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        textSistema.setForeground(new java.awt.Color(255, 255, 255));
        textSistema.setText("EPIC MOUNTAIN SYSTEM");
        jpSistema.add(textSistema, java.awt.BorderLayout.CENTER);

        jpBarra.add(jpSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 260, 50));

        getContentPane().add(jpBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 50));

        jpIconosI.setBackground(new java.awt.Color(51, 51, 51));
        jpIconosI.setLayout(new java.awt.GridLayout(6, 0));

        jpCRM.setBackground(new java.awt.Color(51, 51, 51));
        jpCRM.setLayout(new java.awt.BorderLayout());

        iconCRM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CRM.png"))); // NOI18N
        jpCRM.add(iconCRM, java.awt.BorderLayout.CENTER);

        textCRM.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textCRM.setForeground(new java.awt.Color(255, 255, 255));
        textCRM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCRM.setText("CRM");
        jpCRM.add(textCRM, java.awt.BorderLayout.PAGE_END);

        jpIconosI.add(jpCRM);

        jpVentas.setBackground(new java.awt.Color(51, 51, 51));
        jpVentas.setLayout(new java.awt.BorderLayout());

        textVentas.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textVentas.setForeground(new java.awt.Color(255, 255, 255));
        textVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textVentas.setText("VENTAS");
        jpVentas.add(textVentas, java.awt.BorderLayout.PAGE_END);

        iconVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas.png"))); // NOI18N
        jpVentas.add(iconVentas, java.awt.BorderLayout.CENTER);

        jpIconosI.add(jpVentas);

        jpProvedores.setBackground(new java.awt.Color(51, 51, 51));
        jpProvedores.setLayout(new java.awt.BorderLayout());

        iconProvedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconProvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        jpProvedores.add(iconProvedores, java.awt.BorderLayout.CENTER);

        textProvedores.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textProvedores.setForeground(new java.awt.Color(255, 255, 255));
        textProvedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textProvedores.setText("PROVEDORES");
        jpProvedores.add(textProvedores, java.awt.BorderLayout.PAGE_END);

        jpIconosI.add(jpProvedores);

        jpDeudasP.setBackground(new java.awt.Color(51, 51, 51));
        jpDeudasP.setLayout(new java.awt.BorderLayout());

        iconDeudasP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDeudasP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Deudas_P.png"))); // NOI18N
        jpDeudasP.add(iconDeudasP, java.awt.BorderLayout.CENTER);

        textDeudasP.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textDeudasP.setForeground(new java.awt.Color(255, 255, 255));
        textDeudasP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDeudasP.setText("DEUDAS A P.");
        jpDeudasP.add(textDeudasP, java.awt.BorderLayout.PAGE_END);

        jpIconosI.add(jpDeudasP);

        jpDeudasC.setBackground(new java.awt.Color(51, 51, 51));
        jpDeudasC.setLayout(new java.awt.BorderLayout());

        iconDeudasC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDeudasC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Deudas_C.png"))); // NOI18N
        jpDeudasC.add(iconDeudasC, java.awt.BorderLayout.CENTER);

        textDeudasC.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textDeudasC.setForeground(new java.awt.Color(255, 255, 255));
        textDeudasC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDeudasC.setText("DEUDAS A C.");
        jpDeudasC.add(textDeudasC, java.awt.BorderLayout.PAGE_END);

        jpIconosI.add(jpDeudasC);

        jpEquipo.setBackground(new java.awt.Color(51, 51, 51));
        jpEquipo.setLayout(new java.awt.BorderLayout());

        iconDeudasC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDeudasC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equipo.png"))); // NOI18N
        jpEquipo.add(iconDeudasC1, java.awt.BorderLayout.CENTER);

        textDeudasC1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textDeudasC1.setForeground(new java.awt.Color(255, 255, 255));
        textDeudasC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDeudasC1.setText("EQUIPO Y MOB.");
        jpEquipo.add(textDeudasC1, java.awt.BorderLayout.PAGE_END);

        jpIconosI.add(jpEquipo);

        getContentPane().add(jpIconosI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 1030));

        jpIconosD.setBackground(new java.awt.Color(51, 51, 51));
        jpIconosD.setLayout(new java.awt.GridLayout(6, 0));

        jpCRM1.setBackground(new java.awt.Color(51, 51, 51));
        jpCRM1.setLayout(new java.awt.BorderLayout());

        iconInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario.png"))); // NOI18N
        jpCRM1.add(iconInventario, java.awt.BorderLayout.CENTER);

        textInventario.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textInventario.setForeground(new java.awt.Color(255, 255, 255));
        textInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textInventario.setText("INVENTARIO");
        jpCRM1.add(textInventario, java.awt.BorderLayout.PAGE_END);

        jpIconosD.add(jpCRM1);

        jpInventario.setBackground(new java.awt.Color(51, 51, 51));
        jpInventario.setLayout(new java.awt.BorderLayout());

        textPacks.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textPacks.setForeground(new java.awt.Color(255, 255, 255));
        textPacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textPacks.setText("PACKS");
        jpInventario.add(textPacks, java.awt.BorderLayout.PAGE_END);

        iconPacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPacks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Packs.png"))); // NOI18N
        jpInventario.add(iconPacks, java.awt.BorderLayout.CENTER);

        jpIconosD.add(jpInventario);

        jpSuministros.setBackground(new java.awt.Color(51, 51, 51));
        jpSuministros.setLayout(new java.awt.BorderLayout());

        iconSuministros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Suministros.png"))); // NOI18N
        jpSuministros.add(iconSuministros, java.awt.BorderLayout.CENTER);

        textSuministros.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textSuministros.setForeground(new java.awt.Color(255, 255, 255));
        textSuministros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSuministros.setText("SUMINISTROS");
        jpSuministros.add(textSuministros, java.awt.BorderLayout.PAGE_END);

        jpIconosD.add(jpSuministros);

        jpCuentas.setBackground(new java.awt.Color(51, 51, 51));
        jpCuentas.setLayout(new java.awt.BorderLayout());

        iconCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuentas.png"))); // NOI18N
        jpCuentas.add(iconCuentas, java.awt.BorderLayout.CENTER);

        textCuentas.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textCuentas.setForeground(new java.awt.Color(255, 255, 255));
        textCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCuentas.setText("CUENTAS");
        jpCuentas.add(textCuentas, java.awt.BorderLayout.PAGE_END);

        jpIconosD.add(jpCuentas);

        jpEstrategia.setBackground(new java.awt.Color(51, 51, 51));
        jpEstrategia.setLayout(new java.awt.BorderLayout());

        iconEstrategia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconEstrategia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estrategia.png"))); // NOI18N
        jpEstrategia.add(iconEstrategia, java.awt.BorderLayout.CENTER);

        textEstrategia.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textEstrategia.setForeground(new java.awt.Color(255, 255, 255));
        textEstrategia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEstrategia.setText("ESTRATEGIA");
        jpEstrategia.add(textEstrategia, java.awt.BorderLayout.PAGE_END);

        jpIconosD.add(jpEstrategia);

        jpPlaneacion.setBackground(new java.awt.Color(51, 51, 51));
        jpPlaneacion.setLayout(new java.awt.BorderLayout());

        iconPlaneacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPlaneacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Equipo.png"))); // NOI18N
        jpPlaneacion.add(iconPlaneacion, java.awt.BorderLayout.CENTER);

        textPlaneacion.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textPlaneacion.setForeground(new java.awt.Color(255, 255, 255));
        textPlaneacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textPlaneacion.setText("PLANEACION");
        jpPlaneacion.add(textPlaneacion, java.awt.BorderLayout.PAGE_END);

        jpIconosD.add(jpPlaneacion);

        getContentPane().add(jpIconosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 50, 200, 1030));

        jpCompras.setBackground(new java.awt.Color(51, 51, 51));
        jpCompras.setPreferredSize(new java.awt.Dimension(200, 180));
        jpCompras.setLayout(new java.awt.BorderLayout());

        iconCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Compras.png"))); // NOI18N
        jpCompras.add(iconCompras, java.awt.BorderLayout.CENTER);

        textCompras.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textCompras.setForeground(new java.awt.Color(255, 255, 255));
        textCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCompras.setText("COMPRAS");
        jpCompras.add(textCompras, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jpCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 900, 200, 180));

        jpFacturacion.setBackground(new java.awt.Color(51, 51, 51));
        jpFacturacion.setPreferredSize(new java.awt.Dimension(200, 200));
        jpFacturacion.setLayout(new java.awt.BorderLayout());

        iconFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Facturacion.png"))); // NOI18N
        jpFacturacion.add(iconFacturacion, java.awt.BorderLayout.CENTER);

        textFacturacion.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        textFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        textFacturacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textFacturacion.setText("FACTURACION");
        jpFacturacion.add(textFacturacion, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jpFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 900, 200, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jpCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jpCerrarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCRM;
    private javax.swing.JLabel iconCerrar;
    private javax.swing.JLabel iconCompras;
    private javax.swing.JLabel iconCuentas;
    private javax.swing.JLabel iconDeudasC;
    private javax.swing.JLabel iconDeudasC1;
    private javax.swing.JLabel iconDeudasP;
    private javax.swing.JLabel iconEstrategia;
    private javax.swing.JLabel iconFacturacion;
    private javax.swing.JLabel iconInventario;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconPacks;
    private javax.swing.JLabel iconPlaneacion;
    private javax.swing.JLabel iconProvedores;
    private javax.swing.JLabel iconSuministros;
    private javax.swing.JLabel iconVentas;
    private javax.swing.JPanel jpBarra;
    private javax.swing.JPanel jpCRM;
    private javax.swing.JPanel jpCRM1;
    private javax.swing.JPanel jpCerrar;
    private javax.swing.JPanel jpCompras;
    private javax.swing.JPanel jpCuentas;
    private javax.swing.JPanel jpDeudasC;
    private javax.swing.JPanel jpDeudasP;
    private javax.swing.JPanel jpEquipo;
    private javax.swing.JPanel jpEstrategia;
    private javax.swing.JPanel jpFacturacion;
    private javax.swing.JPanel jpIconosD;
    private javax.swing.JPanel jpIconosI;
    private javax.swing.JPanel jpInventario;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JPanel jpPlaneacion;
    private javax.swing.JPanel jpProvedores;
    private javax.swing.JPanel jpSistema;
    private javax.swing.JPanel jpSuministros;
    private javax.swing.JPanel jpVentas;
    private javax.swing.JLabel textCRM;
    private javax.swing.JLabel textCompras;
    private javax.swing.JLabel textCuentas;
    private javax.swing.JLabel textDeudasC;
    private javax.swing.JLabel textDeudasC1;
    private javax.swing.JLabel textDeudasP;
    private javax.swing.JLabel textEstrategia;
    private javax.swing.JLabel textFacturacion;
    private javax.swing.JLabel textInventario;
    private javax.swing.JLabel textPacks;
    private javax.swing.JLabel textPlaneacion;
    private javax.swing.JLabel textProvedores;
    private javax.swing.JLabel textSistema;
    private javax.swing.JLabel textSuministros;
    private javax.swing.JLabel textVentas;
    // End of variables declaration//GEN-END:variables

}

